name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Flutter action
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.0'
        channel: 'stable'
    - run: flutter --version
